### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by ruelcedeno** [punksta/thecatnative#1]
Hello! I'm a graphic designer and I enjoy contributing to opensource projects. How about a new logo for the app?

**Comment by punksta** [comment]
Hello! It'll be cool! You can update `thecatnative/icon.png` file by pull request or just send it to my email. 
punksta@protonmail.com

**Comment by ruelcedeno** [comment]
What about this? Which color do you link? I'll be happy to make adjustments. 

![kitties_preview](https://user-images.githubusercontent.com/37002265/38016658-e2cb1a4a-3299-11e8-9f63-ac31aa08f91e.png)

**Comment by punksta** [comment]
Nice! I like last one, soft red. Can you also make circled image? I am using current logo as image loader.

**Comment by ruelcedeno** [comment]
Glad you like it! Which sizes do you need?

**Comment by ruelcedeno** [comment]
![1024px_circle](https://user-images.githubusercontent.com/37002265/38019953-351bd52e-32a3-11e8-8186-9a96b3824f30.png)


You access the vectos and png files [here](https://drive.google.com/drive/folders/1GO73HCAG8P6LQDetYXqDLte4bW_OQf4Z?usp=sharing).

**Comment by punksta** [comment]
Nice work, thanks!

**Comment by punksta** [comment]
I will update app in free time and add you to readme.

**Comment by ruelcedeno** [comment]
Happy to hear that sir! Please let me know if you have more graphic requests. Looking forward to contributing more!

**Comment by ruelcedeno** [comment]
![color](https://user-images.githubusercontent.com/37002265/38022783-aac16062-32aa-11e8-98e6-ae37f4cac025.png)

Happy to hear that sir! Please let me know if you have more graphic requests. Looking forward to contributing more!

**Comment by ruelcedeno** [comment]
Here's another version. What do you think? 

![kitties_ver2](https://user-images.githubusercontent.com/37002265/38027823-35f8a6c6-32bb-11e8-9691-c0b5a5beda12.png)

**Comment by punksta** [comment]
@ruelcedeno I find first one modern too much:iphone: :green_apple: 
Second one makes more sense then hearts definitely

**Comment by ruelcedeno** [comment]
I agree. 👍 Let me know if you more suggestions. I'll send the vectors and png files if these are alright. Thanks.

**Comment by punksta** [comment]
![image](https://user-images.githubusercontent.com/13404754/38083523-850afaa6-3352-11e8-98e5-2d60658ff296.png)
these are good. I have nothing to add.

**Comment by ruelcedeno** [comment]
![color](https://user-images.githubusercontent.com/37002265/38092505-9acc32b6-3392-11e8-8ec6-1059e82e4d72.png)


Great! You download the vectors and png files [here](https://drive.google.com/drive/folders/1GO73HCAG8P6LQDetYXqDLte4bW_OQf4Z?usp=sharing). Looking forward to seeing this kitty in the app. :)

**Comment by punksta** [comment]
@ruelcedeno hello again, could you select license for these images?
https://choosealicense.com/non-software/#data-media-etc

**Comment by ruelcedeno** [comment]
I usually use [this license](https://creativecommons.org/choose/) in all my contributions. Is it okay?

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by punksta** [comment]
yes, totally ok!

**Comment by punksta** [comment]
App pushed. thanks again :+1:
